import type { Video } from '@/types'

export const MOCK_VIDEOS: Video[] = [
  {
    id: 'v1',
    url: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnail_url: 'https://picsum.photos/seed/v1/400/700',
    title: 'Trendy Kurti Set - Floral Print',
    title_hi: 'ट्रेंडी कुर्ती सेट - Floral Print',
    description: 'Beautiful floral print kurti set, perfect for all occasions',
    price: 499,
    original_price: 999,
    product_tags: ['kurti', 'fashion', 'women', 'floral'],
    category: 'fashion',
    seller_name: 'Meena Fashion',
    likes_count: 1240,
    language: 'en',
    city_relevance: ['metro', 'tier2'],
    vibe_relevance: ['trendy', 'deal_hunter'],
    mandli_eligible: true,
    mandli_min_count: 5,
    mandli_discount_percent: 20,
    created_at: new Date().toISOString(),
  },
  {
    id: 'v2',
    url: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    thumbnail_url: 'https://picsum.photos/seed/v2/400/700',
    title: 'Non-Stick Kadai 3L',
    title_hi: 'Non-Stick कड़ाई 3L - रसोई के लिए',
    description: 'Premium non-stick kadai for everyday cooking',
    price: 799,
    original_price: 1499,
    product_tags: ['kitchen', 'cookware', 'kadai', 'home'],
    category: 'kitchen',
    seller_name: 'Bharat Kitchen Co',
    likes_count: 892,
    language: 'en',
    city_relevance: ['metro', 'tier2', 'tier3'],
    vibe_relevance: ['home_lover'],
    mandli_eligible: true,
    mandli_min_count: 4,
    mandli_discount_percent: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'v3',
    url: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    thumbnail_url: 'https://picsum.photos/seed/v3/400/700',
    title: 'TWS Earbuds - 40hr Battery',
    title_hi: 'TWS Earbuds - 40 घंटे Battery',
    description: 'Premium sound, 40hr battery, IPX5 waterproof',
    price: 1299,
    original_price: 2999,
    product_tags: ['earbuds', 'electronics', 'audio', 'gadget'],
    category: 'electronics',
    seller_name: 'TechZone India',
    likes_count: 3100,
    language: 'en',
    city_relevance: ['metro', 'tier2'],
    vibe_relevance: ['gadget_freak', 'trendy'],
    mandli_eligible: true,
    mandli_min_count: 6,
    mandli_discount_percent: 25,
    created_at: new Date().toISOString(),
  },
  {
    id: 'v4',
    url: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    thumbnail_url: 'https://picsum.photos/seed/v4/400/700',
    title: 'Printed Bedsheet Set - King Size',
    title_hi: 'Printed Bedsheet Set - King Size',
    description: '100% cotton, vibrant print, king size with pillow covers',
    price: 699,
    original_price: 1299,
    product_tags: ['bedsheet', 'home', 'decor', 'bedroom'],
    category: 'home_decor',
    seller_name: 'Ghar Sajavat',
    likes_count: 567,
    language: 'en',
    city_relevance: ['metro', 'tier2', 'tier3'],
    vibe_relevance: ['home_lover', 'deal_hunter'],
    mandli_eligible: false,
    mandli_min_count: 5,
    mandli_discount_percent: 10,
    created_at: new Date().toISOString(),
  },
  {
    id: 'v5',
    url: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    thumbnail_url: 'https://picsum.photos/seed/v5/400/700',
    title: 'Smartwatch - Health Tracker',
    title_hi: 'Smartwatch - Health Tracker',
    description: 'Track steps, heart rate, sleep. 7-day battery.',
    price: 1999,
    original_price: 4999,
    product_tags: ['smartwatch', 'fitness', 'gadget', 'wearable'],
    category: 'electronics',
    seller_name: 'WristTech India',
    likes_count: 2200,
    language: 'en',
    city_relevance: ['metro'],
    vibe_relevance: ['gadget_freak'],
    mandli_eligible: true,
    mandli_min_count: 5,
    mandli_discount_percent: 20,
    created_at: new Date().toISOString(),
  },
  {
    id: 'v6',
    url: 'https://storage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
    thumbnail_url: 'https://picsum.photos/seed/v6/400/700',
    title: 'Pure Cotton Handloom Saree',
    title_hi: 'साड़ी - शुद्ध कॉटन Handloom',
    description: 'Handloom weaved pure cotton saree with blouse piece',
    price: 1199,
    original_price: 2499,
    product_tags: ['saree', 'fashion', 'women', 'handloom', 'cotton'],
    category: 'fashion',
    seller_name: 'Silk Route India',
    likes_count: 1890,
    language: 'en',
    city_relevance: ['metro', 'tier2', 'tier3'],
    vibe_relevance: ['trendy', 'home_lover'],
    mandli_eligible: true,
    mandli_min_count: 5,
    mandli_discount_percent: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'v7',
    url: 'https://storage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    thumbnail_url: 'https://picsum.photos/seed/v7/400/700',
    title: 'LED String Lights 10m - Diwali Special',
    title_hi: 'LED String Lights 10m - Diwali Special',
    description: '10 meters, 100 LEDs, warm white, for all occasions',
    price: 349,
    original_price: 699,
    product_tags: ['lights', 'decor', 'diwali', 'home', 'festive'],
    category: 'home_decor',
    seller_name: 'Roshan Décor',
    likes_count: 4500,
    language: 'en',
    city_relevance: ['metro', 'tier2', 'tier3'],
    vibe_relevance: ['home_lover', 'deal_hunter'],
    mandli_eligible: true,
    mandli_min_count: 8,
    mandli_discount_percent: 30,
    created_at: new Date().toISOString(),
  },
  {
    id: 'v8',
    url: 'https://storage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4',
    thumbnail_url: 'https://picsum.photos/seed/v8/400/700',
    title: 'Wireless Charger 15W - Fast Charge',
    title_hi: 'Wireless Charger 15W - Fast Charge',
    description: 'Compatible with all Qi devices, LED indicator',
    price: 599,
    original_price: 1299,
    product_tags: ['charger', 'mobile', 'gadget', 'electronics'],
    category: 'electronics',
    seller_name: 'PowerUp India',
    likes_count: 987,
    language: 'en',
    city_relevance: ['metro', 'tier2'],
    vibe_relevance: ['gadget_freak', 'trendy'],
    mandli_eligible: false,
    mandli_min_count: 5,
    mandli_discount_percent: 10,
    created_at: new Date().toISOString(),
  },
]
